import { navy, orange, bg, muted, cardBorder } from './theme';
import { StyleSheet } from 'react-native';

export const C = { navy, orange, bg, muted };

export const ui = StyleSheet.create({
  page: { flex: 1, backgroundColor: bg },
  scroll: { padding: 16, gap: 12, paddingBottom: 32 },
  card: {
    backgroundColor: '#fff',
    borderColor: '#F1F5F9',
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    shadowColor: '#0A192F',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 1,
  },
  title: { fontSize: 20, fontWeight: '800', color: navy },
  subtitle: { fontSize: 13, color: muted, marginTop: 2 },
  row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  input: {
    backgroundColor: '#fff',
    borderColor: '#CBD5E1',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 14,
    height: 48,
    fontSize: 15,
    color: navy,
  },
  label: { fontSize: 12, fontWeight: '700', color: navy, marginTop: 10, marginBottom: 6 },
  btnOrange: { backgroundColor: orange, borderRadius: 10, paddingVertical: 13, alignItems: 'center' },
  btnNavy: { backgroundColor: navy, borderRadius: 10, paddingVertical: 13, alignItems: 'center' },
  btnGhost: { borderColor: cardBorder, borderWidth: 1, borderRadius: 10, paddingVertical: 12, alignItems: 'center' },
  btnText: { color: '#fff', fontWeight: '700', fontSize: 14 },
  btnTextDark: { color: navy, fontWeight: '700', fontSize: 13 },
  btnSm: { paddingVertical: 8, paddingHorizontal: 12, borderRadius: 8 },
  chip: {
    borderColor: cardBorder,
    borderWidth: 1,
    backgroundColor: '#fff',
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 14,
    marginRight: 8,
  },
  chipActive: { backgroundColor: navy, borderColor: navy },
  chipText: { fontSize: 12, fontWeight: '700', color: navy },
  chipTextActive: { color: '#fff' },
  badgeGreen: { backgroundColor: '#ECFDF5', borderRadius: 999, paddingVertical: 4, paddingHorizontal: 10 },
  badgeAmber: { backgroundColor: '#FFF7ED', borderRadius: 999, paddingVertical: 4, paddingHorizontal: 10 },
  badgeGrey: { backgroundColor: '#F1F5F9', borderRadius: 999, paddingVertical: 4, paddingHorizontal: 10 },
  badgeNavy: { backgroundColor: navy, borderRadius: 999, paddingVertical: 4, paddingHorizontal: 10 },
  badgeBlue: { backgroundColor: '#E0F2FE', borderRadius: 999, paddingVertical: 4, paddingHorizontal: 10 },
  badgeTextGreen: { color: '#059669', fontSize: 11, fontWeight: '700' },
  badgeTextAmber: { color: '#EA580C', fontSize: 11, fontWeight: '700' },
  badgeTextGrey: { color: muted, fontSize: 11, fontWeight: '700' },
  badgeTextWhite: { color: '#fff', fontSize: 11, fontWeight: '700' },
  badgeTextBlue: { color: '#0284C7', fontSize: 11, fontWeight: '700' },
  err: { backgroundColor: '#FEF2F2', color: '#B91C1C', borderRadius: 10, padding: 10, fontSize: 13, overflow: 'hidden' },
  ok: { backgroundColor: '#ECFDF5', color: '#059669', borderRadius: 10, padding: 10, fontSize: 13, overflow: 'hidden' },
  hero: { backgroundColor: '#0D1C32', borderRadius: 16, padding: 18 },
  heroBig: { color: '#fff', fontSize: 28, fontWeight: '800' },
  heroSub: { color: '#CBD5E1', fontSize: 12, marginTop: 4 },
  stat: { flex: 1, backgroundColor: '#fff', borderColor: '#F1F5F9', borderWidth: 1, borderRadius: 12, padding: 12, alignItems: 'center' },
  statNum: { fontSize: 18, fontWeight: '800', color: navy },
  statLbl: { fontSize: 11, color: muted },
  link: { color: orange, fontWeight: '700', fontSize: 13 },
});
